### ISSUE TITLE
Consider adding fallback strategy for PrePie devices

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/RxBiometric#1]
Check this: https://github.com/fython/BiometricPromptCompat

Steps for doing this:
- extract code targeted for Android P to one separate class
- hide this class behind the interface and make it default implementation
- create another implementation of the interface using compat code
- choose strategy dynamically depending on Android version
- allow to choose strategy explicitly in the code

**Comment by troyjperales** [comment]
You may want to consider leveraging this: https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/biometric/src/main/java/androidx/biometrics

**Comment by pwittchen** [comment]
Thanks. I'll take a look on that.

pon., 27 sie 2018, 03:53 użytkownik Troy Perales <notifications@github.com>
napisał:

**Comment by ksc91u** [comment]
I have a fork here

https://github.com/ksc91u/RxBiometric

**Comment by pwittchen** [comment]
More references:
- https://developer.android.com/reference/androidx/biometrics/package-summary

**Comment by pwittchen** [comment]
It should be resolved via #9.
